### ISSUE TITLE
Does not work with ansible 2.9.2

### ISSUE THREAD

**Issue by techoover** [ujenmr/ansible-logstash-callback#16]
$ ansible-playbook main.yaml
ERROR! Unexpected Exception, this is probably a bug: 'CallbackModule' object has no attribute '_options'

ansible --version 
ansible 2.9.2

**Comment by ialejandro** [comment]
@techoover I solved here: https://github.com/ujenmr/ansible-logstash-callback/issues/13#issuecomment-624150027
